export interface Article {
  slug: string
  category: string
  title: string
  excerpt: string
  author: string
  authorRole: string
  date: string
  readTime: string
  image: string
  featured?: boolean
}

export const articles: Article[] = [
  {
    slug: 'diferencia-certificacion-acreditacion',
    category: 'Certificación',
    title: 'Certificación vs. acreditación: cuál es la diferencia y por qué importa',
    excerpt: 'Certificación y acreditación se usan como sinónimos pero son cosas muy distintas. Entender la diferencia te evita contratar al organismo equivocado o presentar el documento incorrecto a un cliente.',
    author: 'Equipo Consultto',
    authorRole: 'Especialistas en SGC',
    date: '21 abr 2026',
    readTime: '5 min',
    image: 'https://images.unsplash.com/photo-1606761568499-6d2451b23c66?w=800&q=80',
  },
  {
    slug: 'no-conformidades-acciones-correctivas',
    category: 'Gestión',
    title: 'No conformidades y acciones correctivas: cómo gestionarlas para que realmente mejoren tu sistema',
    excerpt: 'La mayoría de las organizaciones registran no conformidades para cumplir el requisito. Las que mejoran de verdad las usan para aprender. La diferencia está en cómo se analizan las causas y cómo se hace el seguimiento.',
    author: 'Equipo Consultto',
    authorRole: 'Especialistas en SGC',
    date: '21 abr 2026',
    readTime: '7 min',
    image: 'https://images.unsplash.com/photo-1600880292089-90a7e086ee0c?w=800&q=80',
  },
  {
    slug: 'iso-22000-inocuidad-alimentaria',
    category: 'Normas',
    title: 'ISO 22000: qué es, qué exige y cómo certificarse en inocuidad alimentaria',
    excerpt: 'ISO 22000 es la norma de gestión de inocuidad alimentaria más adoptada a nivel global. Si tu empresa produce, procesa o distribuye alimentos, esta norma define los requisitos mínimos para garantizar que lo que llega al consumidor es seguro.',
    author: 'Equipo Consultto',
    authorRole: 'Especialistas en SGC',
    date: '21 abr 2026',
    readTime: '8 min',
    image: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800&q=80',
  },
  {
    slug: 'indicadores-calidad-ejemplos',
    category: 'Gestión',
    title: 'Indicadores de calidad: 15 ejemplos reales y cómo definir los que le sirven a tu empresa',
    excerpt: 'Los indicadores de calidad no son los mismos para todas las empresas. Dependen de tu industria, tu proceso y tus objetivos. Aquí tienes 15 ejemplos reales y el criterio para elegir los que tienen sentido para tu SGC.',
    author: 'Equipo Consultto',
    authorRole: 'Especialistas en SGC',
    date: '21 abr 2026',
    readTime: '7 min',
    image: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&q=80',
  },
  {
    slug: 'certificacion-iso-pymes',
    category: 'Certificación',
    title: 'Certificación ISO para PyMEs: guía práctica para empresas con recursos limitados',
    excerpt: 'Las normas ISO no son solo para grandes corporaciones. Las PyMEs pueden y deben certificarse — de hecho, la certificación puede ser el diferenciador que les abre contratos que antes eran inalcanzables.',
    author: 'Equipo Consultto',
    authorRole: 'Especialistas en SGC',
    date: '21 abr 2026',
    readTime: '7 min',
    image: 'https://images.unsplash.com/photo-1542744173-8e7e53415bb0?w=800&q=80',
  },
  {
    slug: 'que-es-iso-14001',
    category: 'Normas',
    title: 'Qué es ISO 14001 y para qué sirve: guía completa sobre la norma ambiental',
    excerpt: 'ISO 14001 es la norma de gestión ambiental más adoptada del mundo. Te explicamos qué exige, qué beneficios reales da a tu empresa y cómo saber si es el momento correcto para certificarte.',
    author: 'Equipo Consultto',
    authorRole: 'Especialistas en SGC',
    date: '21 abr 2026',
    readTime: '7 min',
    image: 'https://images.unsplash.com/photo-1473341304170-971dccb5ac1e?w=1200&q=80',
  },
  {
    slug: 'que-es-iso-45001',
    category: 'Normas',
    title: 'Qué es ISO 45001: la norma de seguridad y salud en el trabajo explicada',
    excerpt: 'ISO 45001 reemplazó a OHSAS 18001 como el estándar internacional de seguridad laboral. Te explicamos qué exige, a quién aplica y por qué cada vez más empresas la adoptan como decisión de negocio.',
    author: 'Equipo Consultto',
    authorRole: 'Especialistas en SGC',
    date: '21 abr 2026',
    readTime: '7 min',
    image: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=800&q=80',
  },
  {
    slug: 'que-es-sistema-gestion-calidad',
    category: 'Gestión',
    title: 'Qué es un sistema de gestión de calidad (SGC) y cómo implementarlo',
    excerpt: 'Un sistema de gestión de calidad no es un conjunto de documentos ni un manual en el cajón. Es la forma en que una organización planifica, ejecuta, mide y mejora su capacidad para cumplir con los requisitos de sus clientes.',
    author: 'Equipo Consultto',
    authorRole: 'Especialistas en SGC',
    date: '21 abr 2026',
    readTime: '8 min',
    image: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=800&q=80',
  },
  {
    slug: 'auditoria-interna-iso-9001',
    category: 'Auditorías',
    title: 'Cómo hacer una auditoría interna ISO 9001: guía práctica paso a paso',
    excerpt: 'La auditoría interna es uno de los requisitos más importantes de ISO 9001 — y uno de los más mal ejecutados. Te explicamos cómo planearla, ejecutarla y aprovecharla para mejorar el sistema, no solo para cumplir.',
    author: 'Equipo Consultto',
    authorRole: 'Especialistas en SGC',
    date: '21 abr 2026',
    readTime: '8 min',
    image: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=800&q=80',
  },
  {
    slug: 'que-es-iso-27001',
    category: 'Normas',
    title: 'Qué es ISO 27001: todo lo que necesitas saber sobre seguridad de la información',
    excerpt: 'ISO 27001 es la norma internacional de gestión de seguridad de la información. No es solo para empresas de tecnología — cualquier organización que procese datos sensibles tiene razones concretas para implementarla.',
    author: 'Equipo Consultto',
    authorRole: 'Especialistas en SGC',
    date: '21 abr 2026',
    readTime: '8 min',
    image: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?w=800&q=80',
  },
  {
    slug: 'como-certificarse-iso-9001',
    category: 'Certificación',
    title: 'Cómo certificarse en ISO 9001: guía paso a paso para empresas que empiezan desde cero',
    excerpt: 'La certificación ISO 9001 no requiere ser una empresa grande ni tener un departamento de calidad. Te explicamos el proceso completo: desde el diagnóstico inicial hasta salir de la auditoría con el certificado en mano.',
    author: 'Equipo Consultto',
    authorRole: 'Especialistas en SGC',
    date: '21 abr 2026',
    readTime: '9 min',
    image: 'https://images.unsplash.com/photo-1600880292203-757bb62b4baf?w=1200&q=80',
    featured: true,
  },
  {
    slug: 'que-es-iso-9001',
    category: 'Normas',
    title: 'Qué es ISO 9001 y para qué sirve: todo lo que necesitas saber antes de certificarte',
    excerpt: 'ISO 9001 es la norma de gestión de calidad más adoptada del mundo. Pero antes de invertir en la certificación, conviene entender qué es exactamente, qué exige y qué beneficios reales le da a tu empresa.',
    author: 'Equipo Consultto',
    authorRole: 'Especialistas en SGC',
    date: '20 abr 2026',
    readTime: '7 min',
    image: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=800&q=80',
  },
  {
    slug: 'cuanto-cuesta-certificacion-iso-9001',
    category: 'Certificación',
    title: 'Cuánto cuesta la certificación ISO 9001 en México: desglose real de costos',
    excerpt: 'El costo de certificarse en ISO 9001 varía según el tamaño de tu empresa, el organismo certificador y si contratas una consultora. Te damos los números reales para que puedas planear tu inversión.',
    author: 'Equipo Consultto',
    authorRole: 'Especialistas en SGC',
    date: '19 abr 2026',
    readTime: '6 min',
    image: 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=800&q=80',
  },
  {
    slug: 'iso-9001-vs-iso-14001',
    category: 'Normas',
    title: 'ISO 9001 vs ISO 14001: diferencias, similitudes y cómo implementarlas juntas',
    excerpt: 'Muchas empresas llegan a ISO 14001 después de ISO 9001. Las normas comparten estructura, pero tienen objetivos distintos. Te explicamos qué cambia, qué se puede integrar y cuándo tiene sentido hacer las dos.',
    author: 'Equipo Consultto',
    authorRole: 'Especialistas en SGC',
    date: '18 abr 2026',
    readTime: '7 min',
    image: 'https://images.unsplash.com/photo-1497436072909-60f360e1d4b1?w=800&q=80',
  },
  {
    slug: 'tiempo-implementar-iso-9001',
    category: 'Certificación',
    title: 'Cuánto tiempo toma implementar ISO 9001: cronograma real según el tamaño de tu empresa',
    excerpt: 'La respuesta honesta: depende. Pero hay factores concretos que lo determinan. Después de acompañar a más de 200 empresas, podemos decirte qué esperar en cada etapa.',
    author: 'Equipo Consultto',
    authorRole: 'Especialistas en SGC',
    date: '17 abr 2026',
    readTime: '6 min',
    image: 'https://images.unsplash.com/photo-1506784983877-45594efa4cbe?w=800&q=80',
  },
  {
    slug: 'gestion-riesgos-iso-31000',
    category: 'Normas',
    title: 'ISO 31000: cómo implementar un sistema de gestión de riesgos que la alta dirección realmente use',
    excerpt: 'ISO 31000 no es una norma de certificación, es un marco de pensamiento. Las organizaciones que la aplican bien convierten la gestión de riesgos en una ventaja competitiva.',
    author: 'Equipo Consultto',
    authorRole: 'Especialistas en SGC',
    date: '12 abr 2025',
    readTime: '7 min',
    image: 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=1200&q=80',
    featured: true,
  },
  {
    slug: 'revision-por-la-direccion',
    category: 'Gestión',
    title: 'La revisión por la dirección: cómo convertir una obligación de norma en una reunión estratégica',
    excerpt: 'La mayoría de las organizaciones hacen la revisión por la dirección para "cumplir". Las que la hacen bien la usan para tomar decisiones que mejoran el negocio.',
    author: 'Equipo Consultto',
    authorRole: 'Especialistas en SGC',
    date: '11 abr 2025',
    readTime: '6 min',
    image: 'https://images.unsplash.com/photo-1542744173-8e7e53415bb0?w=800&q=80',
  },
  {
    slug: 'iso-27001-seguridad-informacion',
    category: 'Normas',
    title: 'ISO 27001: lo que toda empresa que maneja datos sensibles necesita saber antes de certificarse',
    excerpt: 'ISO 27001 no es exclusiva de empresas tecnológicas. Cualquier organización que procese datos de clientes o proveedores tiene razones de negocio para implementarla.',
    author: 'Equipo Consultto',
    authorRole: 'Especialistas en SGC',
    date: '10 abr 2025',
    readTime: '8 min',
    image: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?w=800&q=80',
  },
  {
    slug: 'pensamiento-basado-en-riesgos',
    category: 'Gestión',
    title: 'Pensamiento basado en riesgos: el concepto de ISO 9001:2015 que más se malinterpreta',
    excerpt: 'No es un registro ni un procedimiento. El pensamiento basado en riesgos es una forma de operar que debe estar integrada en cada proceso, no documentada en un formato aparte.',
    author: 'Equipo Consultto',
    authorRole: 'Especialistas en SGC',
    date: '9 abr 2025',
    readTime: '6 min',
    image: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=800&q=80',
  },
  {
    slug: 'gestion-proveedores-iso-9001',
    category: 'Certificación',
    title: 'Gestión de proveedores bajo ISO 9001: cómo evaluar, calificar y mantener una cadena de suministro confiable',
    excerpt: 'Un sistema de gestión que no controla a sus proveedores tiene un agujero enorme. ISO 9001 exige gestionar la cadena de suministro, pero no dice exactamente cómo.',
    author: 'Equipo Consultto',
    authorRole: 'Especialistas en SGC',
    date: '8 abr 2025',
    readTime: '7 min',
    image: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=800&q=80',
  },
  {
    slug: 'digitalizacion-sgc-por-donde-empezar',
    category: 'Tecnología',
    title: 'Digitalización del SGC: por dónde empezar cuando todo parece urgente',
    excerpt: 'Digitalizar un sistema de gestión sin orden produce el mismo caos que tener carpetas físicas, pero en la nube. La clave está en saber qué digitalizar primero y por qué.',
    author: 'Equipo Consultto',
    authorRole: 'Especialistas en SGC',
    date: '7 abr 2025',
    readTime: '6 min',
    image: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&q=80',
  },
  {
    slug: 'indicadores-programa-auditorias',
    category: 'Auditorías',
    title: 'Cómo medir si tu programa de auditorías internas realmente funciona',
    excerpt: 'Hacer auditorías no garantiza que el sistema mejore. Necesitas indicadores que midan si el programa de auditorías está cumpliendo su propósito real dentro del SGC.',
    author: 'Equipo Consultto',
    authorRole: 'Especialistas en SGC',
    date: '6 abr 2025',
    readTime: '5 min',
    image: 'https://images.unsplash.com/photo-1543286386-713bdd548da4?w=800&q=80',
  },
  {
    slug: 'iso-14001-vs-iso-50001',
    category: 'Normas',
    title: 'ISO 14001 vs. ISO 50001: cuándo implementar una, la otra, o las dos juntas',
    excerpt: 'Aunque ambas normas abordan el impacto ambiental, tienen focos muy distintos. Elegir cuál implementar primero depende de tu industria, tus costos y tus objetivos de negocio.',
    author: 'Equipo Consultto',
    authorRole: 'Especialistas en SGC',
    date: '5 abr 2025',
    readTime: '6 min',
    image: 'https://images.unsplash.com/photo-1497436072909-60f360e1d4b1?w=800&q=80',
  },
  {
    slug: 'auditorias-internas-herramienta-mejora',
    category: 'Auditorías',
    title: 'Auditorías internas: cómo convertirlas en una herramienta de mejora y no en una revisión de cumplimiento',
    excerpt: 'Cuando están bien diseñadas, las auditorías internas son el mecanismo más poderoso para detectar riesgos antes de que llegue el auditor externo.',
    author: 'Equipo Consultto',
    authorRole: 'Especialistas en SGC',
    date: '4 abr 2025',
    readTime: '7 min',
    image: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=1200&q=80',
    featured: true,
  },
  {
    slug: 'que-esperar-auditoria-tercera-parte',
    category: 'Auditorías',
    title: 'Qué esperar de una auditoría de tercera parte: guía para el equipo directivo',
    excerpt: 'La alta dirección suele estar ausente del proceso de auditoría externa — y eso es precisamente lo que los auditores notan.',
    author: 'Equipo Consultto',
    authorRole: 'Especialistas en SGC',
    date: '3 abr 2025',
    readTime: '6 min',
    image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&q=80',
  },
  {
    slug: 'gestion-calidad-industria-alimentaria',
    category: 'Industrias',
    title: 'Gestión de calidad en la industria alimentaria: más allá del cumplimiento regulatorio',
    excerpt: 'Para las empresas del sector alimentos, la calidad no es opcional — es una cuestión de supervivencia. Analizamos cómo integrar los principales esquemas de inocuidad en un sistema coherente.',
    author: 'Equipo Consultto',
    authorRole: 'Especialistas en SGC',
    date: '2 abr 2025',
    readTime: '8 min',
    image: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800&q=80',
  },
  {
    slug: 'construccion-adopta-iso-9001',
    category: 'Industrias',
    title: 'Por qué el sector construcción está adoptando ISO 9001 más rápido que nunca',
    excerpt: 'Las licitaciones públicas y los clientes corporativos están convirtiendo la certificación ISO 9001 en un requisito de entrada al mercado para el sector construcción.',
    author: 'Equipo Consultto',
    authorRole: 'Especialistas en SGC',
    date: '1 abr 2025',
    readTime: '5 min',
    image: 'https://images.unsplash.com/photo-1503387762-592deb58ef4e?w=800&q=80',
  },
  {
    slug: 'recertificacion-iso-mantener-sistema-vivo',
    category: 'Certificación',
    title: 'Recertificación ISO: cómo mantener el sistema vivo entre auditorías sin perder al equipo',
    excerpt: 'El síndrome del "modo auditoría" — activarse solo cuando se acerca el auditor — es la causa principal de pérdida de certificaciones. Aquí explicamos cómo evitarlo.',
    author: 'Equipo Consultto',
    authorRole: 'Especialistas en SGC',
    date: '31 mar 2025',
    readTime: '7 min',
    image: 'https://images.unsplash.com/photo-1600880292089-90a7e086ee0c?w=800&q=80',
  },
  {
    slug: 'kpis-sistema-de-gestion',
    category: 'Gestión',
    title: 'Indicadores de desempeño en un sistema de gestión: cómo elegirlos para que realmente sirvan',
    excerpt: 'Definir los KPIs correctos es una decisión estratégica, no técnica. Explicamos el proceso que usamos para diseñarlos con la alta dirección.',
    author: 'Equipo Consultto',
    authorRole: 'Especialistas en SGC',
    date: '30 mar 2025',
    readTime: '6 min',
    image: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&q=80',
  },
  {
    slug: 'iso-50001-gestion-energia',
    category: 'Normas',
    title: 'ISO 50001: gestión de energía como ventaja competitiva en un entorno de costos crecientes',
    excerpt: 'ISO 50001 pasó de ser una iniciativa ambiental a un argumento financiero concreto. Las organizaciones que la implementan reducen en promedio un 10% su consumo energético en el primer año.',
    author: 'Equipo Consultto',
    authorRole: 'Especialistas en SGC',
    date: '29 mar 2025',
    readTime: '6 min',
    image: 'https://images.unsplash.com/photo-1466611653911-95081537e5b7?w=800&q=80',
  },
  {
    slug: 'software-gestion-documental-vs-sgc',
    category: 'Tecnología',
    title: 'Software de gestión documental vs. plataforma de SGC: cuál necesita tu organización',
    excerpt: 'No es lo mismo almacenar documentos en la nube que gestionar un sistema de calidad. Explicamos qué distingue a ambas soluciones y cuándo cada una tiene sentido.',
    author: 'Equipo Consultto',
    authorRole: 'Especialistas en SGC',
    date: '28 mar 2025',
    readTime: '5 min',
    image: 'https://images.unsplash.com/photo-1517430816045-df4b7de11d1d?w=800&q=80',
  },
  {
    slug: 'cultura-de-calidad-vs-sistema-de-calidad',
    category: 'Gestión',
    title: 'Cultura de calidad vs. sistema de calidad: por qué el primero es más difícil de construir',
    excerpt: 'Un sistema de calidad puede implementarse en meses. Una cultura de calidad tarda años. La diferencia está en cómo los equipos piensan sobre la calidad en el día a día.',
    author: 'Equipo Consultto',
    authorRole: 'Especialistas en SGC',
    date: '27 mar 2025',
    readTime: '8 min',
    image: 'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=800&q=80',
  },
  {
    slug: 'como-preparar-auditoria-iso-9001',
    category: 'Certificación',
    title: 'Cómo preparar a tu organización para una auditoría de certificación ISO 9001 en 90 días',
    excerpt: 'Las organizaciones que fracasan en su primera auditoría confunden tener documentos con tener un sistema. Explicamos el enfoque que usamos con más de 200 empresas.',
    author: 'Equipo Consultto',
    authorRole: 'Especialistas en SGC',
    date: '24 mar 2025',
    readTime: '8 min',
    image: 'https://images.unsplash.com/photo-1600880292203-757bb62b4baf?w=800&q=80',
  },
  {
    slug: 'diferencias-iso-9001-iatf-16949',
    category: 'Normas',
    title: 'ISO 9001 vs. IATF 16949: qué cambia y qué significa para la industria automotriz',
    excerpt: 'La IATF 16949 no es una versión más exigente de ISO 9001 — tiene lógica propia. Entender las diferencias es el primer paso para implementarla sin duplicar esfuerzos.',
    author: 'Equipo Consultto',
    authorRole: 'Especialistas en SGC',
    date: '18 mar 2025',
    readTime: '6 min',
    image: 'https://images.unsplash.com/photo-1565043666747-69f6646db940?w=800&q=80',
  },
  {
    slug: 'ia-en-gestion-de-calidad',
    category: 'Tecnología',
    title: 'El rol de la inteligencia artificial en los sistemas de gestión de calidad modernos',
    excerpt: 'La IA no reemplaza al profesional de calidad — lo potencia. Analizamos cómo integrar agentes de IA para preparar auditorías y mantener el sistema vivo entre certificaciones.',
    author: 'Equipo Consultto',
    authorRole: 'Especialistas en SGC',
    date: '10 mar 2025',
    readTime: '7 min',
    image: 'https://images.unsplash.com/photo-1677442135703-1787eea5ce01?w=800&q=80',
  },
  {
    slug: 'errores-comunes-iso-14001',
    category: 'Certificación',
    title: 'Los cinco errores más comunes al implementar ISO 14001 y cómo evitarlos',
    excerpt: 'Después de acompañar a decenas de organizaciones en certificación ambiental, identificamos los errores que se repiten con más frecuencia — y cómo evitarlos.',
    author: 'Equipo Consultto',
    authorRole: 'Especialistas en SGC',
    date: '3 mar 2025',
    readTime: '5 min',
    image: 'https://images.unsplash.com/photo-1473341304170-971dccb5ac1e?w=800&q=80',
  },
  {
    slug: 'capa-mejora-continua',
    category: 'Gestión',
    title: 'No conformidades efectivas: cómo transformar una no conformidad en una oportunidad de mejora real',
    excerpt: 'En la mayoría de las organizaciones el proceso de no conformidades se convierte en un trámite burocrático. Explicamos qué separa una no conformidad funcional de una que solo existe en papel.',
    author: 'Equipo Consultto',
    authorRole: 'Especialistas en SGC',
    date: '24 feb 2025',
    readTime: '6 min',
    image: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=800&q=80',
  },
  {
    slug: 'iso-45001-seguridad-laboral',
    category: 'Normas',
    title: 'ISO 45001: por qué la seguridad laboral es también una decisión de negocio',
    excerpt: 'Las organizaciones con ISO 45001 no solo reducen accidentes — mejoran su reputación y reducen costos de seguros. Analizamos el caso de negocio detrás de la norma.',
    author: 'Equipo Consultto',
    authorRole: 'Especialistas en SGC',
    date: '17 feb 2025',
    readTime: '5 min',
    image: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=800&q=80',
  },
]

export const categories = ['Todos', 'Certificación', 'Auditorías', 'Normas', 'Industrias', 'Tecnología', 'Gestión']
