export interface Article {
  slug: string
  category: string
  title: string
  excerpt: string
  author: string
  authorRole: string
  date: string
  readTime: string
  image: string
  featured?: boolean
}

export const articles: Article[] = [
  {
    slug: 'auditorias-internas-herramienta-mejora',
    category: 'Auditorías',
    title: 'Auditorías internas: cómo convertirlas en una herramienta de mejora y no en una revisión de cumplimiento',
    excerpt: 'La mayoría de las organizaciones realizan auditorías internas porque la norma lo exige, no porque las encuentren útiles. Eso es un error costoso. Cuando están bien diseñadas, las auditorías internas son el mecanismo más poderoso para detectar riesgos antes de que llegue el auditor externo.',
    author: 'Equipo Consultto',
    authorRole: 'Especialistas en SGC',
    date: '4 abr 2025',
    readTime: '7 min',
    image: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=1200&q=80',
    featured: true,
  },
  {
    slug: 'que-esperar-auditoria-tercera-parte',
    category: 'Auditorías',
    title: 'Qué esperar de una auditoría de tercera parte: guía para el equipo directivo',
    excerpt: 'La alta dirección suele estar ausente del proceso de auditoría externa — y eso es precisamente lo que los auditores notan. En este artículo explicamos qué rol debe jugar el equipo directivo antes, durante y después de una auditoría de certificación, y qué preguntas deben saber responder.',
    author: 'Equipo Consultto',
    authorRole: 'Especialistas en SGC',
    date: '3 abr 2025',
    readTime: '6 min',
    image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&q=80',
  },
  {
    slug: 'gestion-calidad-industria-alimentaria',
    category: 'Industrias',
    title: 'Gestión de calidad en la industria alimentaria: más allá del cumplimiento regulatorio',
    excerpt: 'Para las empresas del sector alimentos, la calidad no es opcional — es una cuestión de supervivencia. Analizamos cómo las organizaciones líderes integran ISO 22000, BRC e FSSC 22000 en un sistema coherente que protege al consumidor y abre mercados internacionales.',
    author: 'Equipo Consultto',
    authorRole: 'Especialistas en SGC',
    date: '2 abr 2025',
    readTime: '8 min',
    image: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800&q=80',
  },
  {
    slug: 'construccion-adopta-iso-9001',
    category: 'Industrias',
    title: 'Por qué el sector construcción está adoptando ISO 9001 más rápido que nunca',
    excerpt: 'Durante años, la construcción fue uno de los sectores más rezagados en adopción de sistemas de gestión. Eso está cambiando. Las exigencias de licitaciones públicas, clientes corporativos y financiamiento internacional están convirtiendo la certificación ISO 9001 en un requisito de entrada al mercado.',
    author: 'Equipo Consultto',
    authorRole: 'Especialistas en SGC',
    date: '1 abr 2025',
    readTime: '5 min',
    image: 'https://images.unsplash.com/photo-1503387762-592deb58ef4e?w=800&q=80',
  },
  {
    slug: 'recertificacion-iso-mantener-sistema-vivo',
    category: 'Certificación',
    title: 'Recertificación ISO: cómo mantener el sistema vivo entre auditorías sin perder al equipo',
    excerpt: 'Conseguir la primera certificación es difícil. Mantenerla en el tiempo es donde la mayoría falla. El síndrome del "modo auditoría" — activarse solo cuando se acerca el auditor externo — es la causa principal de pérdida de certificaciones. Aquí explicamos cómo evitarlo.',
    author: 'Equipo Consultto',
    authorRole: 'Especialistas en SGC',
    date: '31 mar 2025',
    readTime: '7 min',
    image: 'https://images.unsplash.com/photo-1568667256549-094dcc00a0f3?w=800&q=80',
  },
  {
    slug: 'kpis-sistema-de-gestion',
    category: 'Gestión',
    title: 'Indicadores de desempeño en un sistema de gestión: cómo elegirlos para que realmente sirvan',
    excerpt: 'La mayoría de los sistemas de gestión tienen demasiados indicadores que nadie mira, o muy pocos que no reflejan la realidad del negocio. Definir los KPIs correctos es una decisión estratégica, no técnica. Explicamos el proceso que usamos para diseñarlos con la alta dirección.',
    author: 'Equipo Consultto',
    authorRole: 'Especialistas en SGC',
    date: '30 mar 2025',
    readTime: '6 min',
    image: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&q=80',
  },
  {
    slug: 'iso-50001-gestion-energia',
    category: 'Normas',
    title: 'ISO 50001: gestión de energía como ventaja competitiva en un entorno de costos crecientes',
    excerpt: 'Con el costo de la energía en máximos históricos, ISO 50001 ha pasado de ser una iniciativa de responsabilidad ambiental a convertirse en un argumento financiero concreto. Las organizaciones que la implementan reducen en promedio un 10% su consumo energético en el primer año.',
    author: 'Equipo Consultto',
    authorRole: 'Especialistas en SGC',
    date: '29 mar 2025',
    readTime: '6 min',
    image: 'https://images.unsplash.com/photo-1466611653911-95081537e5b7?w=800&q=80',
  },
  {
    slug: 'software-gestion-documental-vs-sgc',
    category: 'Tecnología',
    title: 'Software de gestión documental vs. plataforma de SGC: cuál necesita tu organización',
    excerpt: 'No es lo mismo almacenar documentos en la nube que gestionar un sistema de calidad. La diferencia parece técnica pero tiene consecuencias operativas enormes. Explicamos qué distingue a ambas soluciones y en qué punto del crecimiento organizacional cada una tiene sentido.',
    author: 'Equipo Consultto',
    authorRole: 'Especialistas en SGC',
    date: '28 mar 2025',
    readTime: '5 min',
    image: 'https://images.unsplash.com/photo-1517430816045-df4b7de11d1d?w=800&q=80',
  },
  {
    slug: 'cultura-de-calidad-vs-sistema-de-calidad',
    category: 'Gestión',
    title: 'Cultura de calidad vs. sistema de calidad: por qué el primero es más difícil de construir',
    excerpt: 'Un sistema de calidad puede implementarse en meses. Una cultura de calidad tarda años. La diferencia entre organizaciones que mantienen su certificación con facilidad y las que luchan ciclo tras ciclo no está en sus procedimientos — está en cómo sus equipos piensan sobre la calidad en el día a día.',
    author: 'Equipo Consultto',
    authorRole: 'Especialistas en SGC',
    date: '27 mar 2025',
    readTime: '8 min',
    image: 'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=800&q=80',
  },
  {
    slug: 'como-preparar-auditoria-iso-9001',
    category: 'Certificación',
    title: 'Cómo preparar a tu organización para una auditoría de certificación ISO 9001 en 90 días',
    excerpt: 'Las organizaciones que fracasan en su primera auditoría de certificación comparten un patrón común: confunden tener documentos con tener un sistema. En este artículo explicamos el enfoque que usamos con más de 200 empresas para llegar a la auditoría con evidencia real y estructurada.',
    author: 'Equipo Consultto',
    authorRole: 'Especialistas en SGC',
    date: '24 mar 2025',
    readTime: '8 min',
    image: 'https://images.unsplash.com/photo-1600880292203-757bb62b4baf?w=800&q=80',
  },
  {
    slug: 'diferencias-iso-9001-iatf-16949',
    category: 'Normas',
    title: 'ISO 9001 vs. IATF 16949: qué cambia y qué significa para la industria automotriz',
    excerpt: 'La IATF 16949 no es simplemente una versión más exigente de ISO 9001. Es una norma con lógica propia, diseñada para la cadena de suministro automotriz global. Entender las diferencias es el primer paso para implementarla sin duplicar esfuerzos.',
    author: 'Equipo Consultto',
    authorRole: 'Especialistas en SGC',
    date: '18 mar 2025',
    readTime: '6 min',
    image: 'https://images.unsplash.com/photo-1565043666747-69f6646db940?w=800&q=80',
  },
  {
    slug: 'ia-en-gestion-de-calidad',
    category: 'Tecnología',
    title: 'El rol de la inteligencia artificial en los sistemas de gestión de calidad modernos',
    excerpt: 'La IA no reemplaza al profesional de calidad — lo potencia. Analizamos cómo las organizaciones líderes están integrando agentes de IA para reducir el tiempo de preparación de auditorías, automatizar el seguimiento de no conformidades y mantener su sistema vivo entre certificaciones.',
    author: 'Equipo Consultto',
    authorRole: 'Especialistas en SGC',
    date: '10 mar 2025',
    readTime: '7 min',
    image: 'https://images.unsplash.com/photo-1677442135703-1787eea5ce01?w=800&q=80',
  },
  {
    slug: 'errores-comunes-iso-14001',
    category: 'Certificación',
    title: 'Los cinco errores más comunes al implementar ISO 14001 y cómo evitarlos',
    excerpt: 'Después de acompañar a decenas de organizaciones en su proceso de certificación ambiental, identificamos un conjunto de errores que se repiten con consistencia preocupante. La mayoría son evitables con una planificación adecuada.',
    author: 'Equipo Consultto',
    authorRole: 'Especialistas en SGC',
    date: '3 mar 2025',
    readTime: '5 min',
    image: 'https://images.unsplash.com/photo-1473341304170-971dccb5ac1e?w=800&q=80',
  },
  {
    slug: 'capa-mejora-continua',
    category: 'Gestión',
    title: 'No conformidades efectivas: cómo transformar una no conformidad en una oportunidad de mejora real',
    excerpt: 'El proceso de acciones correctivas y preventivas es uno de los pilares de cualquier sistema de gestión. Sin embargo, en la mayoría de las organizaciones se convierte en un trámite burocrático. Aquí explicamos qué separa una No conformidad funcional de uno que solo existe en papel.',
    author: 'Equipo Consultto',
    authorRole: 'Especialistas en SGC',
    date: '24 feb 2025',
    readTime: '6 min',
    image: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=800&q=80',
  },
  {
    slug: 'iso-45001-seguridad-laboral',
    category: 'Normas',
    title: 'ISO 45001: por qué la seguridad laboral es también una decisión de negocio',
    excerpt: 'Las organizaciones que implementan ISO 45001 no solo reducen accidentes — mejoran su reputación ante clientes, reducen costos de seguros y fortalecen su cultura organizacional. Analizamos el caso de negocio detrás de la norma.',
    author: 'Equipo Consultto',
    authorRole: 'Especialistas en SGC',
    date: '17 feb 2025',
    readTime: '5 min',
    image: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=800&q=80',
  },
]

export const categories = ['Todos', 'Certificación', 'Auditorías', 'Normas', 'Industrias', 'Tecnología', 'Gestión']
