export interface Article {
  slug: string
  category: string
  title: string
  excerpt: string
  author: string
  authorRole: string
  date: string
  readTime: string
  image: string
  featured?: boolean
}

export const articles: Article[] = [
  {
    slug: 'auditorias-internas-herramienta-mejora',
    category: 'Auditorías',
    title: 'Auditorías internas: cómo convertirlas en una herramienta de mejora y no en una revisión de cumplimiento',
    excerpt: 'Cuando están bien diseñadas, las auditorías internas son el mecanismo más poderoso para detectar riesgos antes de que llegue el auditor externo.',
    author: 'Equipo Consultto',
    authorRole: 'Especialistas en SGC',
    date: '4 abr 2025',
    readTime: '7 min',
    image: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=1200&q=80',
    featured: true,
  },
  {
    slug: 'que-esperar-auditoria-tercera-parte',
    category: 'Auditorías',
    title: 'Qué esperar de una auditoría de tercera parte: guía para el equipo directivo',
    excerpt: 'La alta dirección suele estar ausente del proceso de auditoría externa — y eso es precisamente lo que los auditores notan.',
    author: 'Equipo Consultto',
    authorRole: 'Especialistas en SGC',
    date: '3 abr 2025',
    readTime: '6 min',
    image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&q=80',
  },
  {
    slug: 'gestion-calidad-industria-alimentaria',
    category: 'Industrias',
    title: 'Gestión de calidad en la industria alimentaria: más allá del cumplimiento regulatorio',
    excerpt: 'Para las empresas del sector alimentos, la calidad no es opcional — es una cuestión de supervivencia. Analizamos cómo integrar los principales esquemas de inocuidad en un sistema coherente.',
    author: 'Equipo Consultto',
    authorRole: 'Especialistas en SGC',
    date: '2 abr 2025',
    readTime: '8 min',
    image: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800&q=80',
  },
  {
    slug: 'construccion-adopta-iso-9001',
    category: 'Industrias',
    title: 'Por qué el sector construcción está adoptando ISO 9001 más rápido que nunca',
    excerpt: 'Las licitaciones públicas y los clientes corporativos están convirtiendo la certificación ISO 9001 en un requisito de entrada al mercado para el sector construcción.',
    author: 'Equipo Consultto',
    authorRole: 'Especialistas en SGC',
    date: '1 abr 2025',
    readTime: '5 min',
    image: 'https://images.unsplash.com/photo-1503387762-592deb58ef4e?w=800&q=80',
  },
  {
    slug: 'recertificacion-iso-mantener-sistema-vivo',
    category: 'Certificación',
    title: 'Recertificación ISO: cómo mantener el sistema vivo entre auditorías sin perder al equipo',
    excerpt: 'El síndrome del "modo auditoría" — activarse solo cuando se acerca el auditor — es la causa principal de pérdida de certificaciones. Aquí explicamos cómo evitarlo.',
    author: 'Equipo Consultto',
    authorRole: 'Especialistas en SGC',
    date: '31 mar 2025',
    readTime: '7 min',
    image: 'https://images.unsplash.com/photo-1600880292089-90a7e086ee0c?w=800&q=80',
  },
  {
    slug: 'kpis-sistema-de-gestion',
    category: 'Gestión',
    title: 'Indicadores de desempeño en un sistema de gestión: cómo elegirlos para que realmente sirvan',
    excerpt: 'Definir los KPIs correctos es una decisión estratégica, no técnica. Explicamos el proceso que usamos para diseñarlos con la alta dirección.',
    author: 'Equipo Consultto',
    authorRole: 'Especialistas en SGC',
    date: '30 mar 2025',
    readTime: '6 min',
    image: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&q=80',
  },
  {
    slug: 'iso-50001-gestion-energia',
    category: 'Normas',
    title: 'ISO 50001: gestión de energía como ventaja competitiva en un entorno de costos crecientes',
    excerpt: 'ISO 50001 pasó de ser una iniciativa ambiental a un argumento financiero concreto. Las organizaciones que la implementan reducen en promedio un 10% su consumo energético en el primer año.',
    author: 'Equipo Consultto',
    authorRole: 'Especialistas en SGC',
    date: '29 mar 2025',
    readTime: '6 min',
    image: 'https://images.unsplash.com/photo-1466611653911-95081537e5b7?w=800&q=80',
  },
  {
    slug: 'software-gestion-documental-vs-sgc',
    category: 'Tecnología',
    title: 'Software de gestión documental vs. plataforma de SGC: cuál necesita tu organización',
    excerpt: 'No es lo mismo almacenar documentos en la nube que gestionar un sistema de calidad. Explicamos qué distingue a ambas soluciones y cuándo cada una tiene sentido.',
    author: 'Equipo Consultto',
    authorRole: 'Especialistas en SGC',
    date: '28 mar 2025',
    readTime: '5 min',
    image: 'https://images.unsplash.com/photo-1517430816045-df4b7de11d1d?w=800&q=80',
  },
  {
    slug: 'cultura-de-calidad-vs-sistema-de-calidad',
    category: 'Gestión',
    title: 'Cultura de calidad vs. sistema de calidad: por qué el primero es más difícil de construir',
    excerpt: 'Un sistema de calidad puede implementarse en meses. Una cultura de calidad tarda años. La diferencia está en cómo los equipos piensan sobre la calidad en el día a día.',
    author: 'Equipo Consultto',
    authorRole: 'Especialistas en SGC',
    date: '27 mar 2025',
    readTime: '8 min',
    image: 'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=800&q=80',
  },
  {
    slug: 'como-preparar-auditoria-iso-9001',
    category: 'Certificación',
    title: 'Cómo preparar a tu organización para una auditoría de certificación ISO 9001 en 90 días',
    excerpt: 'Las organizaciones que fracasan en su primera auditoría confunden tener documentos con tener un sistema. Explicamos el enfoque que usamos con más de 200 empresas.',
    author: 'Equipo Consultto',
    authorRole: 'Especialistas en SGC',
    date: '24 mar 2025',
    readTime: '8 min',
    image: 'https://images.unsplash.com/photo-1600880292203-757bb62b4baf?w=800&q=80',
  },
  {
    slug: 'diferencias-iso-9001-iatf-16949',
    category: 'Normas',
    title: 'ISO 9001 vs. IATF 16949: qué cambia y qué significa para la industria automotriz',
    excerpt: 'La IATF 16949 no es una versión más exigente de ISO 9001 — tiene lógica propia. Entender las diferencias es el primer paso para implementarla sin duplicar esfuerzos.',
    author: 'Equipo Consultto',
    authorRole: 'Especialistas en SGC',
    date: '18 mar 2025',
    readTime: '6 min',
    image: 'https://images.unsplash.com/photo-1565043666747-69f6646db940?w=800&q=80',
  },
  {
    slug: 'ia-en-gestion-de-calidad',
    category: 'Tecnología',
    title: 'El rol de la inteligencia artificial en los sistemas de gestión de calidad modernos',
    excerpt: 'La IA no reemplaza al profesional de calidad — lo potencia. Analizamos cómo integrar agentes de IA para preparar auditorías y mantener el sistema vivo entre certificaciones.',
    author: 'Equipo Consultto',
    authorRole: 'Especialistas en SGC',
    date: '10 mar 2025',
    readTime: '7 min',
    image: 'https://images.unsplash.com/photo-1677442135703-1787eea5ce01?w=800&q=80',
  },
  {
    slug: 'errores-comunes-iso-14001',
    category: 'Certificación',
    title: 'Los cinco errores más comunes al implementar ISO 14001 y cómo evitarlos',
    excerpt: 'Después de acompañar a decenas de organizaciones en certificación ambiental, identificamos los errores que se repiten con más frecuencia — y cómo evitarlos.',
    author: 'Equipo Consultto',
    authorRole: 'Especialistas en SGC',
    date: '3 mar 2025',
    readTime: '5 min',
    image: 'https://images.unsplash.com/photo-1473341304170-971dccb5ac1e?w=800&q=80',
  },
  {
    slug: 'capa-mejora-continua',
    category: 'Gestión',
    title: 'No conformidades efectivas: cómo transformar una no conformidad en una oportunidad de mejora real',
    excerpt: 'En la mayoría de las organizaciones el proceso de no conformidades se convierte en un trámite burocrático. Explicamos qué separa una no conformidad funcional de una que solo existe en papel.',
    author: 'Equipo Consultto',
    authorRole: 'Especialistas en SGC',
    date: '24 feb 2025',
    readTime: '6 min',
    image: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=800&q=80',
  },
  {
    slug: 'iso-45001-seguridad-laboral',
    category: 'Normas',
    title: 'ISO 45001: por qué la seguridad laboral es también una decisión de negocio',
    excerpt: 'Las organizaciones con ISO 45001 no solo reducen accidentes — mejoran su reputación y reducen costos de seguros. Analizamos el caso de negocio detrás de la norma.',
    author: 'Equipo Consultto',
    authorRole: 'Especialistas en SGC',
    date: '17 feb 2025',
    readTime: '5 min',
    image: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=800&q=80',
  },
]

export const categories = ['Todos', 'Certificación', 'Auditorías', 'Normas', 'Industrias', 'Tecnología', 'Gestión']
